<a href="https://colab.research.google.com/github/CarolGitonga/Generative-AI/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch is an open source machine learning framework that allows you to write your own neural networks and optimize them efficiently.

In [1]:
## Standard libraries
import os
import math
import numpy as np
import time

import torch.nn as nn
import torch.optim as optim

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
from matplotlib.colors import to_rgba
import seaborn as sns
sns.set()

## Progress bar
from tqdm.notebook import tqdm

<ipython-input-1-ef1aac816119>:14: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg', 'pdf') # For export


In [ ]:
import torch
print("Using torch", torch.__version__)

Using torch 2.3.0+cu121


PyTorch provides functions that are stochastic like generating random numbers. However, a very good practice is to setup your code to be reproducible with the exact same random numbers. This is why a seed is set below.

In [ ]:
torch.manual_seed(42) # Setting the seed

When working with neural networks, we will use tensors of various shapes and number of dimensions.Tensors are a generalization of scalars, vectors, and matrices to higher dimensions.They are multi-dimensional arrays that are used extensively in machine learning and deep learning for various computations.

In [ ]:
x = ...
print(x)

Ellipsis


In [ ]:
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# Create a tensor from the nested list
tensor = torch.tensor(nested_list)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
# Create a tensor with random values between 0 and 1 with shape [2, 3, 4]
tensor = torch.rand(2, 3, 4)
print(tensor)

tensor([[[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]],

        [[0.8694, 0.5677, 0.7411, 0.4294],
         [0.8854, 0.5739, 0.2666, 0.6274],
         [0.2696, 0.4414, 0.2969, 0.8317]]])


In [ ]:
# Create a tensor with random values between 0 and 1 with shape [2, 3, 4]
tensor = torch.rand(2, 3, 4)

# Get the shape of the tensor using .shape
shape = tensor.shape
print("Shape using .shape:", shape)

Shape using .shape: torch.Size([2, 3, 4])


To transform a numpy array into a tensor

In [ ]:
# Create a NumPy array
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("NumPy Array:")
print(np_array)

# Convert the NumPy array to a PyTorch tensor
tensor = torch.from_numpy(np_array)
print("PyTorch Tensor:")
print(tensor)

NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


To transform a PyTorch tensor back to a numpy array

In [ ]:
# Create a PyTorch tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("PyTorch Tensor:")
print(tensor)

# Convert the PyTorch tensor to a NumPy array
np_array = tensor.numpy()
print("NumPy Array:")
print(np_array)

PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
NumPy Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Operation of adding two tensors

In [ ]:
# Create two tensors
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
tensor2 = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Add the tensors using the + operator
result_add_operator = tensor1 + tensor2
print("Result of tensor1 + tensor2:")
print(result_add_operator)

# Add the tensors using torch.add()
result_add_function = torch.add(tensor1, tensor2)
print("Result of torch.add(tensor1, tensor2):")
print(result_add_function)

Result of tensor1 + tensor2:
tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])
Result of torch.add(tensor1, tensor2):
tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [ ]:
x1 = torch.rand(2, 3)
x2 = torch.rand(2, 3)
print("X1 (before)", x1)
print("X2 (before)", x2)

x2.add_(x1)
print("X1 (after)", x1)
print("X2 (after)", x2)

X1 (before) tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])
X2 (before) tensor([[0.5315, 0.1587, 0.6542],
        [0.3278, 0.6532, 0.3958]])
X1 (after) tensor([[0.6440, 0.7071, 0.6581],
        [0.4913, 0.8913, 0.1447]])
X2 (after) tensor([[1.1755, 0.8658, 1.3123],
        [0.8191, 1.5445, 0.5406]])


changing the shape of a tensor.

In [ ]:
x = torch.arange(6)
print("X", x)

X tensor([0, 1, 2, 3, 4, 5])


In [ ]:
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [ ]:
x = x.permute(1, 0) # Swapping dimension 0 and 1
print("X", x)

X tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [7]:
x = torch.arange(6)
x = x.view(2, 3)
print("X", x)

X tensor([[0, 1, 2],
        [3, 4, 5]])


In [10]:
x = torch.ones((3,))
print(x.requires_grad)

False


In [11]:
x.requires_grad_(True)
print(x.requires_grad)

True


How to define and train a simple neural network in PyTorch

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(784, 128)  # Fully connected layer 1
        self.fc2 = nn.Linear(128, 64)   # Fully connected layer 2
        self.fc3 = nn.Linear(64, 10)    # Output layer

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# Create an instance of the neural network
model = SimpleNN()

# Define a loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# Dummy data for demonstration (normally you would use a dataset)
inputs = torch.randn(64, 784)  # 64 samples, each with 784 features
labels = torch.randint(0, 10, (64,))  # 64 labels, each a value between 0 and 9

# Training loop
for epoch in range(10):  # Number of epochs
    optimizer.zero_grad()  # Zero the gradients
    outputs = model(inputs)  # Forward pass
    loss = criterion(outputs, labels)  # Compute loss
    loss.backward()  # Backward pass
    optimizer.step()  # Update weights

    print(f'Epoch [{epoch+1}/10], Loss: {loss.item():.4f}')


Epoch [1/10], Loss: 2.3120
Epoch [2/10], Loss: 2.3082
Epoch [3/10], Loss: 2.3045
Epoch [4/10], Loss: 2.3009
Epoch [5/10], Loss: 2.2972
Epoch [6/10], Loss: 2.2936
Epoch [7/10], Loss: 2.2900
Epoch [8/10], Loss: 2.2864
Epoch [9/10], Loss: 2.2829
Epoch [10/10], Loss: 2.2794
